SELECT
  M.SEQ_LOGIN_ID
  , M.SEQ_WORK_USER_MNG_MT_ID
  , (
    SELECT
      COUNT(D.WORK_AUTH_STATUS)
    FROM
      DAILY_WORK_ENTRY_DATA D
    WHERE
      D.WORK_AUTH_STATUS = '10'
      AND D.SEQ_WORK_USER_MNG_MT_ID = M.SEQ_WORK_USER_MNG_MT_ID
      AND DATE_FORMAT(D.BEGIN, '%Y%m') = /* date */202008
  ) NON_AUTH_COUNT
  , (
    SELECT
      COUNT(D.WORK_AUTH_STATUS)
    FROM
      DAILY_WORK_ENTRY_DATA D
    WHERE
      D.WORK_AUTH_STATUS = '20'
      AND D.SEQ_WORK_USER_MNG_MT_ID = M.SEQ_WORK_USER_MNG_MT_ID
      AND DATE_FORMAT(D.BEGIN, '%Y%m') = /* date */202008
  ) AUTH_COUNT
  , (
    SELECT
      COUNT(*)
    FROM
      BUSINESS_CALENDAR_MT BCM
    WHERE
      DATE_FORMAT(BCM.DATE, '%Y%m') = /* date */202008
      AND BCM.BUSINESS_FLG = '1'
  ) BUSINESS_DAY_COUNT
FROM
  WORK_USER_MNG_MT M
ORDER BY
  M.SEQ_WORK_USER_MNG_MT_ID;
