SELECT
  DWED.SEQ_DAILY_WORK_ENTRY_DATA_ID
  , DWED.SEQ_WORK_USER_MNG_MT_ID
  , DWED.BEGIN
  , DWED.END
  , DWED.WORK_AUTH_STATUS
  , DWED.NOTE
  , BCM.DATE
  , BCM.WEEKDAY
  , BCM.BUSINESS_FLG
FROM
  BUSINESS_CALENDAR_MT BCM
    LEFT OUTER JOIN DAILY_WORK_ENTRY_DATA DWED
    ON BCM.DATE = DATE_FORMAT(DWED.BEGIN, '%Y%m%d')
    AND DWED.SEQ_WORK_USER_MNG_MT_ID = /* seqWorkUserMngMtId */1
WHERE
  DATE_FORMAT(BCM.DATE, '%Y%m') = /* date */200810
ORDER BY
  BCM.DATE;
