SELECT
  WUMM.SEQ_LOGIN_ID
  , WUMM.SEQ_WORK_USER_MNG_MT_ID
  , (
    SELECT
      COUNT(DWED.WORK_AUTH_STATUS)
    FROM
      DAILY_WORK_ENTRY_DATA DWED
    WHERE
      DWED.WORK_AUTH_STATUS = '10'
      AND DWED.SEQ_WORK_USER_MNG_MT_ID = WUMM.SEQ_WORK_USER_MNG_MT_ID
      AND DATE_FORMAT(DWED.BEGIN, '%Y%m') = /* date */202008
  ) NON_AUTH_COUNT
  , (
    SELECT
      COUNT(DWED.WORK_AUTH_STATUS)
    FROM
      DAILY_WORK_ENTRY_DATA DWED
    WHERE
      DWED.WORK_AUTH_STATUS = '20'
      AND DWED.SEQ_WORK_USER_MNG_MT_ID = WUMM.SEQ_WORK_USER_MNG_MT_ID
      AND DATE_FORMAT(DWED.BEGIN, '%Y%m') = /* date */202008
  ) AUTH_COUNT
  , (
    SELECT
      COUNT(*)
    FROM
      BUSINESS_CALENDAR_MT BCM
    WHERE
      DATE_FORMAT(BCM.DATE, '%Y%m') = /* date */202008
      AND BCM.BUSINESS_FLG = '1'
  ) BUSINESS_DAY_COUNT
FROM
  WORK_USER_MNG_MT WUMM
ORDER BY
  WUMM.SEQ_WORK_USER_MNG_MT_ID;
