SELECT
  DWED.SEQ_DAILY_WORK_ENTRY_DATA_ID
  , DWED.SEQ_WORK_USER_MNG_MT_ID
  , DWED.BEGIN
  , DWED.END
  , DWED.ACTUAL_TIME
  , DWED.OVER_TIME
  , DWED.LATE_OVER_TIME
  , DWED.HOLIDAY_WORK_TIME
  , DWED.WORK_AUTH_STATUS
  , BCM.DATE
  , BCM.WEEKDAY
  , BCM.BUSINESS_FLG
FROM
  BUSINESS_CALENDAR_MT BCM
  LEFT OUTER JOIN DAILY_WORK_ENTRY_DATA DWED
  ON BCM.DATE = DATE_FORMAT(DWED.BEGIN, '%Y%m%d')
  AND DWED.SEQ_WORK_USER_MNG_MT_ID = (
    SELECT
      WUMM.SEQ_WORK_USER_MNG_MT_ID
    FROM
      WORK_USER_MNG_MT WUMM
    WHERE
      WUMM.SEQ_LOGIN_ID = /* seqLoginId */1
  )
WHERE
  DATE_FORMAT(BCM.DATE, '%Y%m') = /* date */202008
ORDER BY
  BCM.DATE;
