SELECT
  WUMM.SEQ_LOGIN_ID
  , WUMM.SEQ_WORK_USER_MNG_MT_ID
  , WUDM.SEQ_WORK_USER_DETAIL_MT_ID
  , RWT.SEQ_REGULAR_WORK_MT_ID
  , RWT.BEGIN_HOUR
  , RWT.BEGIN_MINUTE
  , RWT.END_HOUR
  , RWT.END_MINUTE
FROM
  WORK_USER_MNG_MT WUMM
  , WORK_USER_DETAIL_MT WUDM
  , REGULAR_WORK_MT RWT
WHERE
  WUMM.SEQ_LOGIN_ID = /* seqLoginId */1
  AND WUDM.SEQ_WORK_USER_DETAIL_MT_ID = WUMM.SEQ_WORK_USER_DETAIL_MT_ID
  AND RWT.SEQ_REGULAR_WORK_MT_ID = WUDM.SEQ_REGULAR_WORK_MT_ID;
