SELECT
  MM.SEQ_LOGIN_ID
  , MM.SEQ_WORK_USER_MNG_MT_ID
  , DM.SEQ_WORK_USER_DETAIL_MT_ID
  , RT.SEQ_REGULAR_WORK_MT_ID
  , RT.BEGIN_HOUR
  , RT.BEGIN_MINUTE
  , RT.END_HOUR
  , RT.END_MINUTE
FROM
  WORK_USER_MNG_MT MM
  , WORK_USER_DETAIL_MT DM
  , REGULAR_WORK_MT RT
WHERE
  MM.SEQ_LOGIN_ID = /* seqLoginId */1
  AND DM.SEQ_WORK_USER_DETAIL_MT_ID = MM.SEQ_WORK_USER_DETAIL_MT_ID
  AND RT.SEQ_REGULAR_WORK_MT_ID = DM.SEQ_REGULAR_WORK_MT_ID;
