SELECT
  MM.SEQ_LOGIN_ID
  , MM.SEQ_WORK_USER_MNG_MT_ID
  , MM.SEQ_WORK_USER_DETAIL_MT_ID
  , RWM.SEQ_REGULAR_WORK_MT_ID
  , RWM.BEGIN_HOUR
  , RWM.BEGIN_MINUTE
  , RWM.END_HOUR
  , RWM.END_MINUTE
  , DM.REG_DATE
FROM
  WORK_USER_MNG_MT MM
  LEFT OUTER JOIN WORK_USER_DETAIL_MT DM
  ON MM.SEQ_WORK_USER_DETAIL_MT_ID = DM.SEQ_WORK_USER_DETAIL_MT_ID
  LEFT OUTER JOIN REGULAR_WORK_MT RWM
  ON DM.SEQ_REGULAR_WORK_MT_ID = RWM.SEQ_REGULAR_WORK_MT_ID
ORDER BY
  MM.SEQ_LOGIN_ID,
  MM.SEQ_WORK_USER_DETAIL_MT_ID DESC;
