-- ログインユーザ情報
CREATE TABLE IF NOT EXISTS LOGIN_USER_DATA (
  -- ログインID
  SEQ_LOGIN_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'ログインID',
  -- パスワード
  PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード',
  -- パスワード有効期限
  PASSWORD_EXPIRE DATE NOT NULL COMMENT 'パスワード有効期限',
  -- アプリ権限
  APP_AUTH VARCHAR(2) NOT NULL COMMENT 'アプリ権限',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);