-- メモユーザ情報
CREATE TABLE IF NOT EXISTS NOTE_USER_DATA (
  -- メモユーザ情報ID
  SEQ_NOTE_USER_DATA_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'メモユーザ情報ID',
  -- ログインID
  SEQ_LOGIN_ID INT NOT NULL COMMENT 'ログインID',
  -- 件名
  TITLE VARCHAR(30) NOT NULL COMMENT '件名',
  -- S3キー
  S3_KEY VARCHAR(100) NOT NULL COMMENT 'S3キー',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);