-- 個別ユーザ情報
CREATE TABLE IF NOT EXISTS PRIVATE_DATA (
  -- ユーザ個別情報ID
  SEQ_PRIVATE_DATA_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'ユーザ個別情報ID',
  -- ログインID
  SEQ_LOGIN_ID INT NOT NULL COMMENT 'ログインID',
  -- メールアドレス
  MAIL_ADDRESS VARBINARY(1024) NOT NULL COMMENT 'メールアドレス',
  -- ユーザ名
  USER_NAME VARCHAR(16) NOT NULL COMMENT 'ユーザ名',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);