-- ログインユーザ情報
DROP TABLE IF EXISTS LOGIN_USER_DATA;
-- 個別ユーザ情報
DROP TABLE IF EXISTS PRIVATE_DATA;
-- 定時情報マスタ
DROP TABLE IF EXISTS REGULAR_WORK_MT;
-- 勤怠ユーザ管理マスタ
DROP TABLE IF EXISTS WORK_USER_MNG_MT;
-- 勤怠ユーザ詳細マスタ
DROP TABLE IF EXISTS WORK_USER_DETAIL_MT;
-- 日別勤怠登録情報
DROP TABLE IF EXISTS DAILY_WORK_ENTRY_DATA;
-- 営業日マスタ
DROP TABLE IF EXISTS BUSINESS_CALENDAR_MT;
-- 勤怠ユーザ履歴マスタ
DROP TABLE IF EXISTS WORK_USER_HIST_MT;
-- メモユーザ情報
DROP TABLE IF EXISTS NOTE_USER_DATA;