SELECT
  WUHT.SEQ_WORK_USER_HIST_MT_ID
  , WUHT.SEQ_WORK_USER_MNG_MT_ID
  , WUHT.SEQ_WORK_USER_DETAIL_MT_ID
  , WUHT.SEQ_LOGIN_ID
  , WUHT.SEQ_REGULAR_WORK_MT_ID
  , RWM.BEGIN_HOUR
  , RWM.BEGIN_MINUTE
  , RWM.END_HOUR
  , RWM.END_MINUTE
  , WUHT.REG_DATE
FROM
  WORK_USER_HIST_MT WUHT
  LEFT OUTER JOIN REGULAR_WORK_MT RWM
    ON WUHT.SEQ_REGULAR_WORK_MT_ID = RWM.SEQ_REGULAR_WORK_MT_ID
ORDER BY
  WUHT.SEQ_LOGIN_ID
  , WUHT.SEQ_REGULAR_WORK_MT_ID;
