SELECT
  LUD.SEQ_LOGIN_ID
  , PD.USER_NAME
  , LUD.APP_AUTH
  , LUD.REG_DATE
FROM
  LOGIN_USER_DATA LUD
  LEFT OUTER JOIN PRIVATE_DATA PD
    ON LUD.SEQ_LOGIN_ID = PD.SEQ_LOGIN_ID
ORDER BY
  LUD.SEQ_LOGIN_ID;
