-- 営業日マスタ
CREATE TABLE IF NOT EXISTS BUSINESS_CALENDAR_MT (
  -- 営業日マスタID
  SEQ_BUSINESS_CALENDAR_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '営業日マスタID',
  -- 日付
  DATE DATE NOT NULL COMMENT '日付',
  -- 曜日
  WEEKDAY VARCHAR(1) NOT NULL COMMENT '曜日',
  -- 営業日フラグ
  BUSINESS_FLG VARCHAR(1) NOT NULL COMMENT '営業日フラグ',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 日別勤怠登録情報
CREATE TABLE IF NOT EXISTS DAILY_WORK_ENTRY_DATA (
  -- 日別勤怠登録情報ID
  SEQ_DAILY_WORK_ENTRY_DATA_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '日別勤怠登録情報ID',
  -- 勤怠ユーザ管理マスタID
  SEQ_WORK_USER_MNG_MT_ID INT NOT NULL COMMENT '勤怠ユーザ管理マスタID',
  -- 始業時間
  BEGIN DATETIME NOT NULL COMMENT '始業時間',
  -- 終業時間
  END DATETIME NOT NULL COMMENT '終業時間',
  -- 承認ステータス
  WORK_AUTH_STATUS VARCHAR(2) NOT NULL COMMENT '承認ステータス',
  -- 備考
  NOTE VARCHAR(256) COMMENT '備考',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- ログインユーザ情報
CREATE TABLE IF NOT EXISTS LOGIN_USER_DATA (
  -- ログインID
  SEQ_LOGIN_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'ログインID',
  -- パスワード
  PASSWORD VARCHAR(64) NOT NULL COMMENT 'パスワード',
  -- パスワード有効期限
  PASSWORD_EXPIRE DATE NOT NULL COMMENT 'パスワード有効期限',
  -- アプリ権限
  APP_AUTH VARCHAR(2) NOT NULL COMMENT 'アプリ権限',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 個別ユーザ情報
CREATE TABLE IF NOT EXISTS PRIVATE_DATA (
  -- ユーザ個別情報ID
  SEQ_PRIVATE_DATA_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'ユーザ個別情報ID',
  -- ログインID
  SEQ_LOGIN_ID INT NOT NULL COMMENT 'ログインID',
  -- メールアドレス
  MAIL_ADDRESS VARBINARY(1024) NOT NULL COMMENT 'メールアドレス',
  -- ユーザ名
  USER_NAME VARCHAR(16) NOT NULL COMMENT 'ユーザ名',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 定時情報マスタ
CREATE TABLE IF NOT EXISTS REGULAR_WORK_MT (
  -- 定時情報マスタID
  SEQ_REGULAR_WORK_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '定時情報マスタID',
  -- 始業時間(時)
  BEGIN_HOUR INT NOT NULL COMMENT '始業時間(時)',
  -- 始業時間(分)
  BEGIN_MINUTE INT NOT NULL COMMENT '始業時間(分)',
  -- 終業時間(時)
  END_HOUR INT NOT NULL COMMENT '終業時間(時)',
  -- 終業時間(分)
  END_MINUTE INT NOT NULL COMMENT '終業時間(分)',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 勤怠ユーザ詳細マスタ
CREATE TABLE IF NOT EXISTS WORK_USER_DETAIL_MT (
  -- 勤怠ユーザ詳細マスタID
  SEQ_WORK_USER_DETAIL_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '勤怠ユーザ詳細マスタID',
  -- 定時情報マスタID
  SEQ_REGULAR_WORK_MT_ID INT NOT NULL COMMENT '定時情報マスタID',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 勤怠ユーザ履歴マスタ
CREATE TABLE IF NOT EXISTS WORK_USER_HIST_MT (
  -- 勤怠ユーザ履歴マスタID
  SEQ_WORK_USER_HIST_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '勤怠ユーザ履歴マスタID',
  -- 勤怠ユーザ管理マスタID
  SEQ_WORK_USER_MNG_MT_ID INT NOT NULL COMMENT '勤怠ユーザ管理マスタID',
  -- 勤怠ユーザ詳細マスタID
  SEQ_WORK_USER_DETAIL_MT_ID INT NOT NULL COMMENT '勤怠ユーザ詳細マスタID',
  -- ログインID
  SEQ_LOGIN_ID INT NOT NULL COMMENT 'ログインID',
  -- 定時情報マスタID
  SEQ_REGULAR_WORK_MT_ID INT NOT NULL COMMENT '定時情報マスタID',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);

-- 勤怠ユーザ管理マスタ
CREATE TABLE IF NOT EXISTS WORK_USER_MNG_MT (
  -- 勤怠ユーザ管理マスタID
  SEQ_WORK_USER_MNG_MT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '勤怠ユーザ管理マスタID',
  -- ログインID
  SEQ_LOGIN_ID INT NOT NULL COMMENT 'ログインID',
  -- 勤怠ユーザ詳細マスタID
  SEQ_WORK_USER_DETAIL_MT_ID INT NOT NULL COMMENT '勤怠ユーザ詳細マスタID',
  -- バージョン情報
  VERSION INT NOT NULL COMMENT 'バージョン情報',
  -- 登録日時
  REG_DATE DATETIME NOT NULL COMMENT '登録日時',
  -- 更新日時
  UPDATE_DATE DATETIME NOT NULL COMMENT '更新日時'
);